---
- name: step one - take payload as input
  hosts: all
  gather_facts: false
  tasks:
  - debug:
      var: payload
  - ansible.builtin.set_stats: 
      data:
        payload:
          extra:
            generated_hostname: "{{ lookup('password', '/dev/null length=10 chars=ascii_lowercase,digits') }}.labo.ovh"
