---
- name: step one - take payload as input
  hosts: all
  gather_facts: false
  tasks:
  - debug:
      var: payload_original
  - ansible.builtin.set_stats: 
      data:
        payload_extra:
          generated_hostname: "{{ lookup('password', '/dev/null length=10 chars=ascii_lowercase,digits') }}.labo.ovh"
