--- 
- name: using input
  hosts: all
  gather_facts: false
  tasks:
  - name: In memory inventory
    ansible.builtin.add_host:
      hostname: '{{ generated_hostname }}'

  - name: Try to run something on the newly generated VM
    debug:
      msg: This is a test
