--- 
- name: using input
  hosts: localhost
  gather_facts: false
  tasks:
  - name: In memory inventory
    ansible.builtin.add_host:
      ansible_hostname: '{{ generated_hostname }}'
      name: new_machine
      ansible_connection: ssh

  - name: Try to run something on the newly generated VM
    dnf:
      name: tcpdump
      state: present
    delegate_to: new_machine
