---
- name: Print all variables passed to the playbook
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Display all vars for the host
      debug:
        var: hostvars[inventory_hostname]
